import { Inter } from 'next/font/google'

// styles
import Reset from '@/styles/reset'
import GlobalStyle from '@/styles/globalStyle'
import Normalize from '@/styles/normalize'
// providers
import StyleProvider from '@/providers/styledProvider'
import QueryClientProvider from '@/providers/reactQueryProvider'
import RecoilProvider from '@/providers/recoilProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Тестовое задание',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }) => {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <QueryClientProvider>
          <RecoilProvider>
            <StyleProvider>
              <Reset />
              <Normalize />
              <GlobalStyle />
              {children}
            </StyleProvider>
          </RecoilProvider>
        </QueryClientProvider>
      </body>
    </html>
  )
}

export default RootLayout
